### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by candideu** [berrysauce/reacty#9]
Hello! I found this app on Alternativeto and wanted to try it out. Is this project still active? The URL doesn't appear to work.

**Comment by berrysauce** [comment]
Hey! Sorry, the project is inactive. It wasn't used that much by its users.

**Comment by candideu** [comment]
@berrysauce That's too bad... Any way of self-hosting this on Deta? I noticed that [Basketball](https://github.com/berrysauce/basketball) has the one-click deploy, but I'm not familiar with the platform.

**Comment by berrysauce** [comment]
> @berrysauce That's too bad... Any way of self-hosting this on Deta? I noticed that [Basketball](https://github.com/berrysauce/basketball) has the one-click deploy, but I'm not familiar with the platform.

It's pretty easy. They don't cost money to use, so you can sign up for free and once you've signed you can deploy reacty via their CLI. You may need to make some configuration adjustments, especially on the ENV Variable front.

I think the only ENV Var you need is `DETA_TOKEN`. To get that you just need to generate a token in your Deta dashboard.

If you need help setting it up, I might have time for a call this weekend!
